label: Patrick McNeal
language: en
gender: ''
style: "LibriVox \xB7 Neilson"
use_cases:
- narrator
- audiobook
- storyteller
duration_s: 10.0
source: "LibriVox \xB7 Patrick McNeal reads Junior Classics Volume 1: Fairy and Wonder\
  \ Tales"
