"""Pin the 2026-05-18 (round 7) ``image_to_kenburns_clip`` frame-cap fix.

The bug
-------

Pre-fix the helper called ``ffmpeg -loop 1 -t clip_t -i image -vf
<zoompan d=N> -r fps`` where ``N = clip_t * fps``. zoompan with
``d=N`` emits N OUTPUT frames per INPUT frame. With ``-loop 1 -t
clip_t -i image`` (no ``-framerate`` set) the input stream defaults
to ~25 fps × clip_t seconds ≈ 60–75 input frames. zoompan therefore
emitted N × (clip_t × 25) ≈ 5000 output frames. The downstream
``-r fps`` only adjusted the output framerate; it did NOT cap the
number of frames. Final mp4 duration: ~107s per "2.5s" clip.

Where it bit us
---------------

``ai_beat_slideshow._stitch_images`` concat-demuxed 13 of these
107-second clips into a ~1391-second slideshow.mp4. Then
``BeatSlideshowMux.mux`` capped output to ``audio.duration_s`` ≈ 41s
via ``-t``, so the viewer saw only the FIRST ~38% of clip 0
(= ``beat_000.png`` Ken-Burns'd slowly for the entire 41s).
Render-41f77152 ketchup-on-slow-cooked-beef-stew had 13 distinct
PNGs generated by z-image-turbo and the user reported "literally the
same image just getting zoomed slowly" — that's why.

The fix
-------

Replace ``-t clip_t -loop 1 -i image -vf <zoompan> -r fps`` with
``-loop 1 -framerate fps -i image -vf <zoompan> -frames:v frames``
where ``frames = round(clip_t * fps)``. The ``-frames:v`` cap stops
ffmpeg after exactly the requested number of frames regardless of
zoompan's per-input-frame emission count. Output duration becomes
exactly ``frames / fps`` ≈ ``clip_t`` seconds.

Equivalent legacy correctness
-----------------------------

The legacy ``compose()`` and ``compose_clips()`` paths used
``_kenburns_filter`` inside a ``filter_complex`` chain that ended
with ``xfade`` at audio-anchored offsets. xfade trimmed each
``[v{i}]`` to its offset boundary, so the per-clip overproduction was
hidden by the downstream crossfade (just wasted CPU). The
``compose_hybrid`` path (line ~1221) also called this helper but
fed outputs into ``compose_clips``, where the same xfade trim
masked the bug. ``ai_beat_slideshow._stitch_images`` uses ``-c
copy`` concat with no downstream xfade — that's what finally
exposed the broken duration.
"""
from __future__ import annotations

import subprocess
import sys
import tempfile
import unittest
from pathlib import Path

from PIL import Image

from tests._helpers import PROJECT_ROOT  # noqa: F401 — sets sys.path


def _have_ffmpeg() -> bool:
    try:
        subprocess.run(
            ["ffmpeg", "-version"], capture_output=True, check=True
        )
        return True
    except (FileNotFoundError, subprocess.CalledProcessError):
        return False


def _make_test_png(path: Path, color: tuple[int, int, int] = (200, 50, 50)) -> Path:
    Image.new("RGB", (1080, 1920), color).save(path)
    return path


def _probe_duration_s(path: Path) -> float:
    r = subprocess.run(
        [
            "ffprobe", "-v", "error",
            "-show_entries", "format=duration",
            "-of", "default=nw=1:nk=1",
            str(path),
        ],
        capture_output=True, text=True, check=True,
    )
    return float(r.stdout.strip())


def _probe_frame_count(path: Path) -> int:
    r = subprocess.run(
        [
            "ffprobe", "-v", "error", "-count_frames",
            "-select_streams", "v:0",
            "-show_entries", "stream=nb_read_frames",
            "-of", "default=nw=1:nk=1",
            str(path),
        ],
        capture_output=True, text=True, check=True,
    )
    return int(r.stdout.strip())


@unittest.skipUnless(_have_ffmpeg(), "ffmpeg not on PATH")
class ImageToKenburnsClipDurationTest(unittest.TestCase):
    """Regression for the 2026-05-18 ``image_to_kenburns_clip`` bug
    where each clip was ~50× too long because zoompan's per-input-frame
    emission was uncapped."""

    def test_2s_request_produces_close_to_2s_output(self):
        """A request for a 2.0s clip must produce a clip whose duration
        is within ±0.2s of the request (allow rounding for XFADE pad
        and integer-frame quantisation). Pre-fix it was ~107s."""
        from pipeline.compose import image_to_kenburns_clip  # noqa: PLC0415

        with tempfile.TemporaryDirectory() as td:
            img = _make_test_png(Path(td) / "img.png")
            out = Path(td) / "clip.mp4"
            image_to_kenburns_clip(img, 2.0, out)

            dur = _probe_duration_s(out)
            # Expected: 2.0 + XFADE(0.08) = 2.08s, rounded to 62 frames
            # at 30fps → 62/30 = 2.067s. Pre-fix: ~107s. Hard upper
            # bound at 4s catches the pre-fix bug definitively.
            self.assertLess(
                dur, 4.0,
                f"clip duration {dur:.2f}s indicates the pre-2026-05-18 "
                f"per-input-frame zoompan blowup bug has returned — "
                f"image_to_kenburns_clip must cap output with -frames:v",
            )
            self.assertGreater(
                dur, 1.5,
                f"clip duration {dur:.2f}s is too short — the helper "
                f"under-produced frames",
            )

    def test_clip_duration_scales_with_request(self):
        """Doubling the request roughly doubles the output duration."""
        from pipeline.compose import image_to_kenburns_clip  # noqa: PLC0415

        with tempfile.TemporaryDirectory() as td:
            img = _make_test_png(Path(td) / "img.png")
            short_out = Path(td) / "short.mp4"
            long_out = Path(td) / "long.mp4"
            image_to_kenburns_clip(img, 1.0, short_out)
            image_to_kenburns_clip(img, 3.0, long_out)

            short_dur = _probe_duration_s(short_out)
            long_dur = _probe_duration_s(long_out)
            # 3.0s request should be roughly 2-3× the 1.0s output.
            ratio = long_dur / short_dur
            self.assertGreater(
                ratio, 1.8,
                f"long/short ratio {ratio:.2f} too low — durations are "
                f"not scaling with the request (short={short_dur:.2f}s, "
                f"long={long_dur:.2f}s)",
            )
            self.assertLess(
                ratio, 4.0,
                f"long/short ratio {ratio:.2f} too high — likely the "
                f"per-input-frame blowup is back",
            )

    def test_thirteen_clip_concat_matches_sum(self):
        """End-to-end: 13 clips at 2s each concat'd should produce a
        slideshow ≈ 13 × 2.08s ≈ 27s, not 13 × 107s ≈ 1391s. This is
        the actual production scenario render-41f77152 hit."""
        from pipeline.compose import image_to_kenburns_clip  # noqa: PLC0415
        from pipeline.render.shared.concat_safe import concat_file_line  # noqa: PLC0415

        with tempfile.TemporaryDirectory() as td:
            tdp = Path(td)
            clips = []
            for i in range(13):
                img = _make_test_png(
                    tdp / f"img_{i:02d}.png",
                    color=(50 + i * 15, 100, 200 - i * 10),
                )
                clip = tdp / f"clip_{i:02d}.mp4"
                image_to_kenburns_clip(img, 2.0, clip)
                clips.append(clip)

            concat_list = tdp / "list.txt"
            concat_list.write_text(
                "\n".join(concat_file_line(p) for p in clips)
            )
            slideshow = tdp / "slideshow.mp4"
            subprocess.run(
                [
                    "ffmpeg", "-y",
                    "-f", "concat", "-safe", "0",
                    "-i", str(concat_list),
                    "-c", "copy",
                    str(slideshow),
                ],
                capture_output=True, check=True,
            )
            slideshow_dur = _probe_duration_s(slideshow)
            # Expected: 13 × ~2.07s = ~26.9s. Pre-fix: 13 × ~107s =
            # ~1391s. Anything > 60s means the bug is back.
            self.assertLess(
                slideshow_dur, 60.0,
                f"13-clip slideshow is {slideshow_dur:.0f}s — pre-2026-05-18 "
                f"bug would have produced ~1391s; current threshold catches "
                f"any meaningful regression",
            )
            self.assertGreater(
                slideshow_dur, 20.0,
                f"13-clip slideshow is only {slideshow_dur:.0f}s — clips "
                f"are under-produced",
            )


if __name__ == "__main__":
    unittest.main()
