"""Stage 7 — compose final 9:16 vertical video via ffmpeg.

Each image gets its beat's exact duration, with Ken Burns zoom+pan and
crossfade between images. Captions are rendered as PNGs (see captions.py)
and overlaid with ffmpeg's `overlay` filter, since this Homebrew ffmpeg
build lacks `drawtext` and `subtitles`/libass.

Three principles enforced here (see DESIGN.md §14):

* **#1 Audio-anchored timeline** — every per-beat duration in the video
  is derived from ``beat.start`` (the ASR-aligned audio timestamp), not
  from accumulating ``beat.duration``. Inter-beat silence (the natural
  pauses ASR detects between sentences) used to get dropped on the floor,
  so the video drifted ~1.5s ahead of the audio over a 20s Short. Now
  each image plays from the audio moment its beat starts to the audio
  moment the next beat starts, with the xfade ending exactly on that
  boundary — caption flips at that boundary too, no shift.
* **#6 Visible motion** — one center-only punch-in zoom per beat. The
  zoom completes inside ``PUNCH_FRAMES`` output frames at the start of
  each beat, then holds. The punch lands during/just after the xfade so
  the motion reads as part of the cut rather than fighting it. Pan
  variants were removed — multiple directions per beat made every cut a
  fresh re-orientation and masked the sync.
* **#40 Compose is the contract** — captions and per-beat artefacts are
  NOT trusted from prior runs. At the top of every compose call we
  wipe ``cache_dir/caption_*.png`` and ``cache_dir/word_*.png``, plus
  any ``img_NN.png`` whose index ≥ ``len(beats)``. Then we always
  regenerate captions fresh from the current ``beats.json``. The
  off-by-one between cached artefacts and beats that produced multi-
  second caption drift on earlier renders is structurally impossible
  under this contract — there is no caption cache to drift.
"""

from __future__ import annotations

import os
import re
import subprocess
from pathlib import Path

from .beats import Beat
from . import captions
from . import telemetry as _tlm


def wipe_stale_per_beat_artefacts(cache_dir: Path, n_beats: int) -> None:
    """Public wrapper around the historical per-compose wipe.

    Exposed so make_shorts.py can perform the wipe BEFORE the image
    stage runs — that way a background thread can pre-render word
    captions in parallel with image generation without having its
    output erased when compose() starts. compose() still calls
    _wipe_stale_per_beat_artefacts internally as a safety net for
    callers that don't pre-wipe.
    """
    _wipe_stale_per_beat_artefacts(cache_dir, n_beats)


def prerender_word_captions(beats: list[Beat], cache_dir: Path) -> int:
    """Render every word_NNNN.png the upcoming compose() call will need,
    skipping files that already exist on disk.

    Word PNGs are pure CPU work (PIL text + outline) and depend only
    on the beat list — no GPU dependency. Calling this from a
    background thread during image gen overlaps the ~7-15s of caption
    work with the ~10-60 minute image stage, eliminating it from the
    serial post-image-stage compose budget.

    Idempotent: safe to call twice; safe to call inside compose()
    after this function has already populated the directory.
    """
    cache_dir.mkdir(parents=True, exist_ok=True)
    n_rendered = 0
    gi = 0
    for beat in beats:
        for w in beat.words:
            text = (w.text or "").strip()
            if not text:
                continue
            wp = cache_dir / f"word_{gi:04d}.png"
            if not wp.exists():
                captions.render_word_caption(text, wp, canvas_w=WIDTH)
                n_rendered += 1
            gi += 1
    return n_rendered


def _wipe_stale_per_beat_artefacts(cache_dir: Path, n_beats: int) -> None:
    """Delete cached per-beat / per-word artefacts.

    Always wipes ``caption_*.png`` and ``word_*.png`` (these are
    re-rendered fresh on every compose run; cheap to regenerate, the
    cache only ever leaks bugs). Selectively wipes ``img_NN.png``
    where NN ≥ ``n_beats`` — those are guaranteed-stale images from a
    previous beat-split that had more beats than the current one.
    Images at NN < n_beats are kept (they're regenerated by
    make_shorts.py when prompts.json changes via its own cache logic).
    """
    if not cache_dir.exists():
        return
    n_dropped = 0
    # Class-of-bug guard (2026-05-03 hathi-raja render): the caption
    # prerender runs on a background thread (make_shorts.py:1286) while
    # compose's wipe runs on the main thread when compose() starts.
    # Race: glob lists word_NN.png that the prerender thread has
    # written, but the prerender keeps churning so file timing is loose;
    # unlink() can race with PIL's atomic-replace save and surface a
    # FileNotFoundError. Treat unlink errors as "already gone" — that's
    # the wipe's intent anyway. Same defensive pattern for img_*.png.
    for pat in ("caption_*.png", "word_*.png", "rank_chip_*.png", "closer_row_*.png"):
        for f in cache_dir.glob(pat):
            try:
                f.unlink()
                n_dropped += 1
            except FileNotFoundError:
                pass
    for f in cache_dir.glob("img_*.png"):
        m = re.search(r"img_(\d+)\.png$", f.name)
        if m and int(m.group(1)) >= n_beats:
            try:
                f.unlink()
                n_dropped += 1
            except FileNotFoundError:
                pass
    # closer_panel.png is regenerated from cfg["closer_format"] on every
    # render; leaving the prior version in place was the path that let
    # an old/buggy panel persist into a re-compose. Wipe unconditionally
    # — the cost is one trivial PIL render per pass. (Critic 2026-05.)
    closer_panel = cache_dir / "closer_panel.png"
    if closer_panel.exists():
        closer_panel.unlink()
        n_dropped += 1
    if n_dropped:
        print(f"[compose] wiped {n_dropped} stale per-beat artefacts")


def _materialise_rank_chips(
    rank_chips: list[tuple[int, int, int | Path]] | None,
    cache_dir: Path,
) -> list[tuple[int, int, Path]] | None:
    """Render rank chip PNGs after the wipe and return path-bearing specs.

    Accepts either ``(start_beat_idx, end_beat_idx, rank_int)`` (the
    new shape, where compose owns the PNG lifecycle) or
    ``(start_beat_idx, end_beat_idx, png_path)`` (legacy / pre-wipe-aware
    callers). Returns the path-bearing form, with PNGs freshly rendered
    so the wipe at the top of compose can't delete them out from under
    ffmpeg. Mirrors the render_closer_panel-after-wipe contract.
    """
    if not rank_chips:
        return rank_chips
    out: list[tuple[int, int, Path]] = []
    for start_idx, end_idx, third in rank_chips:
        if isinstance(third, int):
            png = cache_dir / f"rank_chip_{third}.png"
            captions.render_rank_chip(third, png)
            out.append((start_idx, end_idx, png))
        else:
            png = Path(third)
            if not png.exists():
                m = re.search(r"rank_chip_(\d+)\.png$", png.name)
                if m:
                    captions.render_rank_chip(int(m.group(1)), png)
            out.append((start_idx, end_idx, png))
    return out


WIDTH = 1080
HEIGHT = 1920
FPS = 30
# XFADE bridges through a SOLID BLACK frame (transition=fadeblack),
# not a content cross-dissolve. This prevents the ghost double-exposure
# artifact (Principle #16) where two independently-generated AI images
# alpha-blend mid-transition into a melted-face frame.
#
# Critic finding 2026-05: at 0.18s × 22 beat boundaries, the cumulative
# black-flash time on a 23-beat Short was ~4s, which viewers reported
# as "the video keeps feeling like it ended". A 1-fps sample of the
# rendered mp4 caught 5 frames mid-fade — same complaint as the inter-
# paragraph silence regression. 0.08s = ~3 frames in/out at 30fps —
# enough to crossbleed the model-image discontinuity without registering
# as a black flash to the viewer.
XFADE = 0.08  # seconds

# Punch-in zoom: ramp from 1.0 → ZOOM_MAX over PUNCH_FRAMES, then a
# slow continued drift to ZOOM_DRIFT_END across the rest of the clip
# so no two frames are ever pixel-identical (Principle #15: static
# pixel runs >1s are prohibited — frozen-frame collapse craters
# retention even when the audio is good).
PUNCH_FRAMES = 12  # ~0.4s at 30fps
ZOOM_MAX = 1.12
ZOOM_DRIFT_END = 1.16  # +4% over the post-punch hold


def _kenburns_filter(clip_duration: float, beat_index: int) -> str:
    """zoompan: a punch-in followed by a slow drift, never frozen."""
    del beat_index  # all beats share one motion shape
    frames = max(1, int(round(clip_duration * FPS)))
    z_max = ZOOM_MAX
    z_end = ZOOM_DRIFT_END
    drift_frames = max(1, frames - PUNCH_FRAMES)
    z_expr = (
        f"if(lt(on,{PUNCH_FRAMES}),"
        f"1+({z_max}-1)*on/{PUNCH_FRAMES},"
        f"{z_max}+({z_end}-{z_max})*(on-{PUNCH_FRAMES})/{drift_frames})"
    )
    return (
        f"scale=2400:-1,"
        f"zoompan=z='{z_expr}':"
        f"x='iw/2-(iw/zoom/2)':y='ih/2-(ih/zoom/2)':"
        f"d={frames}:s={WIDTH}x{HEIGHT}:fps={FPS},"
        f"setsar=1"
    )


def _video_timing(beats: list[Beat]) -> tuple[list[float], list[float]]:
    """Anchor the video timeline to ``beat.start`` (audio time).

    Returns ``(video_start, video_dur)``: per-beat onset and length in
    the OUTPUT timeline. Beat 0 is anchored at video t=0 (so any
    leading TTS silence sits *before* image 0 cleanly disappears — the
    image is up before the first word lands), and every subsequent
    beat onset matches its audio ``beat.start``. The last beat extends
    to its own ``end`` (tail-hold is appended separately by tpad).

    Without this, ``sum(beat.duration)`` ignores inter-beat silence
    that ASR captures between sentences — drift accrues and by the
    last beat the video runs ~1s ahead of the audio.
    """
    n = len(beats)
    if n == 0:
        return [], []
    video_start = [0.0]
    for i in range(1, n):
        video_start.append(beats[i].start)
    video_dur: list[float] = []
    for i in range(n):
        if i + 1 < n:
            video_dur.append(video_start[i + 1] - video_start[i])
        else:
            video_dur.append(beats[i].end - video_start[i])
    return video_start, video_dur


def _caption_window(
    beats: list[Beat],
    video_start: list[float],
    video_dur: list[float],
    i: int,
) -> tuple[float, float]:
    """When caption[i] is on screen.

    Anchored to the audio timeline: caption flips ON at the moment the
    beat's first spoken word lands and OFF at the next beat's first
    word — no XFADE/2 shift. The image's xfade completes at the same
    boundary, so caption + image transitions land at the same instant.
    """
    is_last = i == len(beats) - 1
    start = video_start[i]
    end = video_start[i] + video_dur[i] if is_last else video_start[i + 1]
    return max(0.0, start), end


def _beat_overlaps_closer(beat_text: str, closer_format: str | None) -> bool:
    """Heuristic: does this beat's caption text overlap the closer panel?

    Class-of-bug fix: when the spoken closer ("LIKE if YTA, COMMENT if NTA")
    arrives as a caption AND the panel is up, the screen has duplicate text
    in two styles fighting for attention. Suppress the caption for beats
    that mostly contain closer-panel words.
    """
    if not closer_format:
        return False
    panel_words = {
        w.lower().strip(",.?!")
        for w in closer_format.split()
        if len(w) > 2 and w.lower() not in {"if", "the", "and", "or"}
    }
    if not panel_words:
        return False
    beat_words = {
        w.lower().strip(",.?!")
        for w in beat_text.split()
        if len(w) > 2
    }
    if not beat_words:
        return False
    overlap = panel_words & beat_words
    # If half or more of the substantive words in the beat are also in the
    # panel, suppress the caption.
    return len(overlap) / len(beat_words) >= 0.5


# Word-level karaoke captions: position relative to frame.
# Slightly above vertical centre, away from the closer-panel safe zone.
_WORD_CAPTION_Y_FRAC = 0.45


def _compose_with_word_captions(
    *,
    image_paths: list[Path],
    beats: list[Beat],
    audio_path: Path,
    out_path: Path,
    cache_dir: Path,
    video_start: list[float],
    video_dur: list[float],
    tail_hold_s: float,
    closer_panel_path: Path | None,
    closer_format: str | None,
    closer_caption_rows: list[Path] | None = None,
    pass_label: str,
    rank_chips: list[tuple[int, Path]] | None = None,
) -> Path:
    """Compose the Short with per-word karaoke captions (the default path).

    For each word in each beat, render a tight transparent PNG of the
    word and overlay it centre-frame for the word's [start, end]
    interval. One word at a time on screen; modern Shorts caption look.

    Sync architecture: word PNGs are written FRESH on every compose
    call to ``cache_dir/word_NNNN.png`` and their indices are local to
    this run. There is NO cross-run cache that could drift.
    """
    # Flatten all words across all beats with their global indices.
    all_words: list[tuple[int, float, float, str]] = []  # (global_idx, start, end, text)
    panel_token_set: set[str] = set()
    if closer_format:
        panel_token_set = {
            w.lower().strip(",.?!")
            for w in closer_format.split()
            if len(w) > 2 and w.lower() not in {"if", "the", "and", "or"}
        }
    for beat in beats:
        for w in beat.words:
            text = (w.text or "").strip()
            if not text:
                continue
            all_words.append((len(all_words), float(w.start), float(w.end), text))

    # Render one PNG per word, skipping any that the make_shorts.py
    # background prerender thread already produced. The wipe at the
    # top of compose() is a safety net; when make_shorts.py pre-wipes
    # then prerenders captions during image gen, we want those PNGs
    # to survive into here. Idempotent on file presence — same text
    # written twice would be byte-identical.
    word_pngs: list[Path] = []
    for gi, _ws, _we, text in all_words:
        wp = cache_dir / f"word_{gi:04d}.png"
        if not wp.exists():
            captions.render_word_caption(text, wp, canvas_w=WIDTH)
        word_pngs.append(wp)

    n_images = len(image_paths)
    last_idx = len(beats) - 1
    has_tail = tail_hold_s > 0
    # No closer overlay anymore (see comment further down). Keep the
    # ignore-the-arg semantics so existing callers that still pass
    # closer_caption_rows don't break.
    closer_row_paths: list[Path] = []
    has_closer = False

    # ---- Build ffmpeg command ---------------------------------------
    inputs: list[str] = []
    filter_chains: list[str] = []

    # Image inputs + Ken Burns chain.
    for i, img in enumerate(image_paths):
        clip_t = video_dur[i] + XFADE
        inputs += ["-loop", "1", "-t", f"{clip_t:.3f}", "-i", str(img)]
        filter_chains.append(f"[{i}:v]{_kenburns_filter(clip_t, i)}[v{i}]")

    # Crossfade chain — audio-anchored offsets.
    if len(beats) == 1:
        filter_chains.append("[v0]copy[vchain]")
    else:
        prev = "v0"
        for i in range(1, len(beats)):
            label = f"x{i}" if i < len(beats) - 1 else "vchain"
            offset = max(0.0, video_start[i] - XFADE)
            filter_chains.append(
                f"[{prev}][v{i}]xfade=transition=fadeblack:duration={XFADE}:"
                f"offset={offset:.3f}[{label}]"
            )
            prev = label

    # Word-PNG inputs (one per word). Each is looped so ffmpeg has a
    # frame to overlay during the word's enable window.
    word_input_idx_start = n_images
    last_audio_t = (video_start[last_idx] + video_dur[last_idx]) + tail_hold_s
    for gi, ws, we, _text in all_words:
        # Loop PNG long enough to cover from t=0 to its end (overlay
        # filter only displays during enable window).
        loop_t = max(0.5, we + 0.5)
        inputs += ["-loop", "1", "-t", f"{loop_t:.3f}", "-i", str(word_pngs[gi])]

    # Per-word overlays. enable='between(t, ws, we)' shows each word
    # only during its spoken interval.
    prev_label = "vchain"
    n_words = len(all_words)
    has_chips = bool(rank_chips)
    final_label = "vout" if not has_chips else "v_pre_chips"
    for k, (gi, ws, we, text) in enumerate(all_words):
        is_last_word = k == n_words - 1
        more_filters_after = is_last_word and (has_tail or has_chips)
        out_label = (
            f"vw{k}" if (not is_last_word or more_filters_after) else final_label
        )

        # Per-word captions run for every beat including the last —
        # there is no closer overlay competing for the y=864 position
        # anymore (see comment further down). The narrator's spoken
        # words are the only text on screen.

        in_label = f"{word_input_idx_start + gi}:v"
        word_y = int(HEIGHT * _WORD_CAPTION_Y_FRAC)
        filter_chains.append(
            f"[{prev_label}][{in_label}]overlay=x=(W-w)/2:y={word_y}:"
            f"enable='between(t,{ws:.3f},{we:.3f})'"
            f"[{out_label}]"
        )
        prev_label = out_label

    # Tail hold (freeze last frame). With the like+subscribe icons
    # now embedded into the last beat's image, the tail-hold lets the
    # viewer see those icons for tail_hold_s before the video ends.
    if has_tail:
        next_label = "vtail" if has_chips else final_label
        filter_chains.append(
            f"[{prev_label}]tpad=stop_mode=clone:"
            f"stop_duration={tail_hold_s:.3f}[{next_label}]"
        )
        prev_label = next_label

    # NOTE: there is no longer any "closer" overlay / panel / caption
    # row. User feedback 2026-05-02: captions are ONLY the narrated
    # spoken word; the YouTube-style like + subscribe icons are
    # embedded INTO the last beat's image at the diffusion-prompt level
    # (see make_shorts.py — last-beat icon injection). Compose has no
    # closer-specific overlay path. closer_caption_rows is kept as a
    # parameter for backwards-compat callers but is intentionally
    # ignored.

    # Rank chip overlays (one per rank, spanning rank-start to next-rank-start).
    chip_specs: list[tuple[int, int, float, float]] = []
    if has_chips:
        chip_input_idx = n_images + n_words + len(closer_row_paths)
        for k, (start_idx, end_idx, png_path) in enumerate(rank_chips):
            if not (0 <= start_idx < len(beats)):
                print(f"[compose] rank chip start_idx {start_idx} out of range — skipping")
                continue
            t_from = video_start[start_idx]
            if 0 <= end_idx < len(beats):
                t_to = video_start[end_idx]
            else:
                t_to = video_start[start_idx] + video_dur[start_idx]
            chip_dur = (t_to - t_from) + 0.5
            inputs += [
                "-loop", "1",
                "-t", f"{chip_dur:.3f}",
                "-i", str(png_path),
            ]
            chip_specs.append((chip_input_idx + k, start_idx, t_from, t_to))
        CHIP_X, CHIP_Y = 60, 200
        for k, (in_idx, _b_idx, t_from, t_to) in enumerate(chip_specs):
            is_last_chip = k == len(chip_specs) - 1
            out_label = "vout" if is_last_chip else f"vrank{k}"
            filter_chains.append(
                f"[{prev_label}][{in_idx}:v]overlay=x={CHIP_X}:y={CHIP_Y}:"
                f"enable='between(t,{t_from:.3f},{t_to:.3f})'"
                f"[{out_label}]"
            )
            prev_label = out_label

    filter_complex = ";".join(filter_chains)
    audio_idx = n_images + n_words + len(closer_row_paths) + len(chip_specs)
    max_duration = max(b.end for b in beats) + 0.4 + tail_hold_s

    cmd = [
        "ffmpeg", "-y",
        *inputs,
        "-i", str(audio_path),
        "-filter_complex", filter_complex,
        "-map", "[vout]",
        "-map", f"{audio_idx}:a",
        "-c:v", "libx264",
        "-pix_fmt", "yuv420p",
        "-r", str(FPS),
        "-c:a", "aac",
        "-b:a", "192k",
        "-movflags", "+faststart",
        "-t", f"{max_duration:.3f}",
    ]
    if tail_hold_s > 0:
        cmd += ["-af", f"apad=pad_dur={tail_hold_s:.3f}"]
    cmd += [str(out_path)]
    print(f"[compose] running ffmpeg with {n_words} per-word overlays…")
    with _tlm.timed(
        "ffmpeg_compose",
        category="pipeline",
        job_id=os.environ.get("YTFACTORY_JOB_ID") or None,
        metadata={
            # `phase` is the canonical key as of 2026-05-10 (latency
            # dashboard reads it). `pass` retained for back-compat with
            # historical events parsed by old code paths.
            "phase": pass_label,
            "pass": pass_label,
            "caption_mode": "word",
            "n_inputs": len(image_paths),
            "n_words": n_words,
            "duration_s": round(max_duration, 2),
            "tail_hold_s": tail_hold_s,
        },
    ):
        result = subprocess.run(cmd, capture_output=True, text=True)
    if result.returncode != 0:
        print("[compose] ffmpeg stderr (last 3000 chars):")
        print(result.stderr[-3000:])
        raise RuntimeError(f"ffmpeg failed (exit {result.returncode})")
    print(f"[compose] wrote {out_path}")
    return out_path


def compose(
    image_paths: list[Path],
    beats: list[Beat],
    audio_path: Path,
    out_path: Path,
    cache_dir: Path,
    tail_hold_s: float = 0.0,
    closer_panel_path: Path | None = None,
    closer_format: str | None = None,
    pass_label: str = "compose",
    caption_mode: str = "word",
    rank_chips: list[tuple[int, Path]] | None = None,
) -> Path:
    """Render the final Short.

    ``tail_hold_s`` freezes the last frame for that many extra seconds
    after narration ends, padding audio with silence. Use it so the
    closer caption + panel stay on screen long enough for the viewer
    to react.

    ``closer_panel_path`` is an optional PNG (RGBA) overlaid during the
    final beat + tail hold — typically a "LIKE if YTA / COMMENT if NTA"
    CTA panel for AITA channels.

    ``caption_mode``: ``"word"`` (default) renders one PNG per spoken
    word, displayed centre-vertical for the word's exact spoken
    interval (modern Shorts/TikTok karaoke style — strongest retention
    per OpusClip/Submagic 2026 benchmarks, and makes residual sync
    drift invisible at the word grain). ``"beat"`` falls back to the
    legacy per-beat block at the bottom of the frame.
    """
    # Pre-flight: image-count must match beat count, fail loud not silent.
    assert len(image_paths) == len(beats), \
        f"image-count drift: {len(image_paths)} images vs {len(beats)} beats"
    out_path.parent.mkdir(parents=True, exist_ok=True)

    # Compose is the contract (Principle #40): wipe any stale per-beat
    # artefacts from a previous run before rendering. The off-by-one
    # bug between cached caption_NN.png files and a re-split beats.json
    # is structurally impossible under this contract — captions will
    # be regenerated fresh from the current beats below.
    _wipe_stale_per_beat_artefacts(cache_dir, len(beats))

    # No closer overlay. User feedback 2026-05-02: captions are ONLY
    # the narrated spoken word; the YouTube-style like + subscribe
    # iconography is embedded INTO the last beat's image at the
    # diffusion-prompt level (see make_shorts.py last-beat icon
    # injection). closer_format / closer_panel_path are accepted for
    # back-compat but ignored — no panel or row PNGs are rendered or
    # overlaid by compose anymore.
    closer_caption_rows: list[Path] = []
    closer_panel_path = None

    # Same render-after-wipe contract for tier-list rank chips. Caller
    # passes (start_beat_idx, end_beat_idx, rank_int) — compose owns
    # the PNG lifecycle so the wipe can never delete a chip out from
    # under ffmpeg. Param is normalised to (start, end, png_path) for
    # the inner compose paths that follow.
    rank_chips = _materialise_rank_chips(rank_chips, cache_dir)

    video_start, video_dur = _video_timing(beats)

    if caption_mode == "word":
        return _compose_with_word_captions(
            image_paths=image_paths,
            beats=beats,
            audio_path=audio_path,
            out_path=out_path,
            cache_dir=cache_dir,
            video_start=video_start,
            video_dur=video_dur,
            tail_hold_s=tail_hold_s,
            closer_panel_path=closer_panel_path,
            closer_format=closer_format,
            closer_caption_rows=closer_caption_rows,
            pass_label=pass_label,
            rank_chips=rank_chips,
        )

    # ---- Legacy per-beat caption mode (kept for backwards compat) ----

    # 1. Render caption PNGs (one per beat). Always re-render — never
    #    short-circuit on disk presence. The wipe above already cleared
    #    any stale ones; this loop ensures every caption_NN.png comes
    #    from the CURRENT beats.json.
    caption_paths: list[Path] = []
    for i, beat in enumerate(beats):
        cp = cache_dir / f"caption_{i:02d}.png"
        captions.render_beat_caption(beat, cp, canvas_w=WIDTH, canvas_h=320)
        caption_paths.append(cp)

    # 2. Build ffmpeg input list and per-image Ken Burns chain.
    #    Each image is held for video_dur[i] + XFADE so the next xfade
    #    has the overlap it needs.
    inputs: list[str] = []
    filter_chains: list[str] = []
    for i, img in enumerate(image_paths):
        clip_t = video_dur[i] + XFADE
        inputs += ["-loop", "1", "-t", f"{clip_t:.3f}", "-i", str(img)]
        filter_chains.append(f"[{i}:v]{_kenburns_filter(clip_t, i)}[v{i}]")

    # 3. Crossfade in sequence. Offset is anchored to the audio
    #    timeline: xfade between beat i-1 and beat i ends exactly at
    #    video_start[i] (= the beat's first spoken word).
    if len(beats) == 1:
        filter_chains.append("[v0]copy[vchain]")
    else:
        prev = "v0"
        for i in range(1, len(beats)):
            label = f"x{i}" if i < len(beats) - 1 else "vchain"
            offset = max(0.0, video_start[i] - XFADE)
            filter_chains.append(
                f"[{prev}][v{i}]xfade=transition=fadeblack:duration={XFADE}:"
                f"offset={offset:.3f}[{label}]"
            )
            prev = label

    # 4. Caption inputs (looped long enough to cover their on-screen
    #    window; +XFADE buffer to be safe against any rounding).
    n_images = len(image_paths)
    caption_input_idx_start = n_images
    for i, cp in enumerate(caption_paths):
        inputs += [
            "-loop", "1",
            "-t", f"{video_dur[i] + XFADE:.3f}",
            "-i", str(cp),
        ]

    # 5. Overlay each caption PNG anchored to the audio timeline
    #    (Principle #1). Caption flips at the beat's first spoken word;
    #    no XFADE/2 shift. Skip beats whose text overlaps the closer
    #    panel content (avoid duplicate text on screen).
    prev_label = "vchain"
    last_idx = len(beats) - 1
    has_tail = tail_hold_s > 0
    has_closer = closer_panel_path is not None
    for i, beat in enumerate(beats):
        is_chain_end = i == last_idx
        # If we're tail-holding or overlaying a closer panel, the chain
        # has more filters after this caption — don't sink to 'vout' yet.
        more_filters_after = is_chain_end and (has_tail or has_closer)
        out_label = (
            f"vc{i}" if (i < last_idx or more_filters_after) else "vout"
        )

        # Suppress redundant caption when the closer panel is up and
        # the spoken text overlaps the panel content.
        if has_closer and _beat_overlaps_closer(beat.text, closer_format):  # pragma: no cover
            # Skip the overlay but still need to forward the label.
            filter_chains.append(f"[{prev_label}]copy[{out_label}]")
            prev_label = out_label
            continue

        in_label = f"{caption_input_idx_start + i}:v"
        cap_start, cap_end = _caption_window(beats, video_start, video_dur, i)
        # Extend the closer caption window through the tail hold so the
        # caption stays burned in across the frozen frames.
        if is_chain_end and tail_hold_s > 0:
            cap_end += tail_hold_s
        # Position caption near the bottom with a fixed safe-zone gap.
        # Principle #25 (NEW): read the actual caption PNG height per
        # beat (it varies with line count after the adaptive canvas fix
        # in captions.py) so long captions never clip the frame edge.
        # Reserves 240px below the caption for the YouTube Shorts UI
        # (progress bar, channel chip, like/comment buttons).
        BOTTOM_SAFE_ZONE = 240
        try:
            from PIL import Image as _PIL
            with _PIL.open(caption_paths[i]) as _cap_img:
                _cap_h = _cap_img.height
        except Exception:
            _cap_h = 320  # legacy fallback
        y_pos = HEIGHT - _cap_h - BOTTOM_SAFE_ZONE
        filter_chains.append(
            f"[{prev_label}][{in_label}]overlay=x=0:y={y_pos}:"
            f"enable='between(t,{cap_start:.3f},{cap_end:.3f})'"
            f"[{out_label}]"
        )
        prev_label = out_label

    # 6. Optional: hold the last frame for tail_hold_s extra seconds.
    if has_tail:
        next_label = "vtail" if has_closer else "vout"
        filter_chains.append(
            f"[{prev_label}]tpad=stop_mode=clone:"
            f"stop_duration={tail_hold_s:.3f}[{next_label}]"
        )
        prev_label = next_label

    # 7. Optional: closer-panel overlay during the final beat + tail.
    closer_input_idx = None
    if has_closer:  # pragma: no cover
        # Each prior -i block (image or caption) contributes exactly one
        # input stream index. Images: n_images. Captions: n_beats. Next
        # free index = n_images + n_beats.
        closer_input_idx = n_images + len(beats)
        # Display window: from start of last beat through end of the
        # entire output (including tail hold). Use a very large upper
        # bound for the enable expression — ffmpeg ignores end > video
        # duration. This guarantees the panel stays through tpad's
        # frozen frames.
        last_start, _ = _caption_window(beats, video_start, video_dur, last_idx)
        # Loop the panel image long enough to cover the whole tail.
        # Output video length = video_start[last] + video_dur[last]
        # (= beats[last].end if no drift). Plus a 1s safety margin and
        # the tail-hold pad.
        last_end_video = video_start[last_idx] + video_dur[last_idx]
        closer_duration = (last_end_video - last_start) + 1.0 + tail_hold_s
        inputs += [
            "-loop", "1",
            "-t", f"{closer_duration:.3f}",
            "-i", str(closer_panel_path),
        ]
        # Position the closer panel in the safe-area zone above the
        # character's face. With panel height 360px, y=80 puts the
        # bottom edge at 440px in a 1920px frame — well above where
        # faces typically render in our 1080×1920 portrait crops.
        # (Class-of-bug fix from critic: panel at y=320 was covering
        # the face; previously y=320 covered y=320..840 = the face row.)
        closer_y = 80
        # Use a generous upper bound so the panel persists through the
        # frozen-frame tail (ffmpeg ignores enable times past EOS).
        filter_chains.append(
            f"[{prev_label}][{closer_input_idx}:v]overlay=x=0:y={closer_y}:"
            f"enable='gte(t,{last_start:.3f})'"
            f"[vout]"
        )

    filter_complex = ";".join(filter_chains)
    # Audio is the last -i added: n_images + n_beats + (1 if closer).
    audio_idx = n_images + len(beats) + (1 if has_closer else 0)

    # Cap output duration to the last beat's end + a small tail, so the
    # video doesn't include trailing silent frames if the audio file is
    # longer than the spoken narration.
    max_duration = max(b.end for b in beats) + 0.4 + tail_hold_s

    cmd = [
        "ffmpeg", "-y",
        *inputs,
        "-i", str(audio_path),
        "-filter_complex", filter_complex,
        "-map", "[vout]",
        "-map", f"{audio_idx}:a",
        "-c:v", "libx264",
        "-pix_fmt", "yuv420p",
        "-r", str(FPS),
        "-c:a", "aac",
        "-b:a", "192k",
        "-movflags", "+faststart",
        "-t", f"{max_duration:.3f}",
    ]
    if tail_hold_s > 0:
        cmd += ["-af", f"apad=pad_dur={tail_hold_s:.3f}"]
    cmd += [str(out_path)]
    print("[compose] running ffmpeg…")
    with _tlm.timed(
        "ffmpeg_compose",
        category="pipeline",
        job_id=os.environ.get("YTFACTORY_JOB_ID") or None,
        metadata={
            "phase": pass_label,
            "pass": pass_label,
            "n_inputs": len(image_paths),
            "duration_s": round(max_duration, 2),
            "tail_hold_s": tail_hold_s,
        },
    ) as t:
        result = subprocess.run(cmd, capture_output=True, text=True)
        t.add(metadata={"return_code": result.returncode})
        if result.returncode != 0:
            print("[compose] ffmpeg stderr (last 3000 chars):")
            print(result.stderr[-3000:])
            raise RuntimeError(f"ffmpeg failed (exit {result.returncode})")
    print(f"[compose] wrote {out_path}")
    return out_path


def _clip_filter(clip_duration: float) -> str:
    """Filter chain for a per-beat animation clip.

    Unlike the slideshow path, animated clips don't need Ken Burns —
    the motion is already in the frames. We just upscale to the output
    resolution, normalise SAR, and trim/pad to ``clip_duration``
    (which already includes the XFADE overlap) so the next clip's
    xfade has overlap to consume.
    """
    target = clip_duration
    return (
        f"scale={WIDTH}:{HEIGHT}:force_original_aspect_ratio=increase,"
        f"crop={WIDTH}:{HEIGHT},"
        f"setsar=1,"
        f"fps={FPS},"
        # Loop short clips, then trim — handles the case where AnimateDiff
        # produced a 2.0s clip but the beat is 2.6s.
        f"loop=loop=-1:size=32767:start=0,"
        f"trim=duration={target:.3f},"
        f"setpts=PTS-STARTPTS"
    )


def image_to_kenburns_clip(
    image_path: Path,
    duration_s: float,
    out_path: Path,
) -> Path:
    """Render a still image to a 1080x1920 Ken Burns mp4 clip.

    Used by ``compose_hybrid`` to convert the slideshow path's per-beat
    images into mp4 clips so they can interleave with real footage clips
    inside ``compose_clips``. The motion shape mirrors what
    ``compose()`` applies inline (punch-in then drift) so a hybrid Short
    feels visually consistent across image beats and footage beats.
    """
    # Pad the rendered length by XFADE so the next clip in the chain has
    # frames to crossfade against — same accounting compose_clips uses
    # when it pulls clips into its xfade graph.
    clip_t = max(0.5, duration_s + XFADE)
    vf = _kenburns_filter(clip_t, 0)
    out_path.parent.mkdir(parents=True, exist_ok=True)
    cmd = [
        "ffmpeg", "-y",
        "-loop", "1",
        "-t", f"{clip_t:.3f}",
        "-i", str(image_path),
        "-vf", vf,
        "-r", str(FPS),
        "-c:v", "libx264",
        "-pix_fmt", "yuv420p",
        "-an",
        "-movflags", "+faststart",
        str(out_path),
    ]
    result = subprocess.run(cmd, capture_output=True, text=True)
    if result.returncode != 0:
        print("[compose] image_to_kenburns_clip ffmpeg stderr (last 2000):")
        print(result.stderr[-2000:])
        raise RuntimeError(
            f"image→clip ffmpeg failed (exit {result.returncode})"
        )
    return out_path


def _ffprobe_duration(path: Path) -> float:
    result = subprocess.run(
        [
            "ffprobe", "-v", "error",
            "-show_entries", "format=duration",
            "-of", "default=noprint_wrappers=1:nokey=1",
            str(path),
        ],
        capture_output=True, text=True, check=True,
    )
    return float(result.stdout.strip())


def _extend_beats_for_footage(
    *,
    beats: list[Beat],
    beat_resolutions: list[tuple[str, Path]],
    audio_path: Path,
    cache_dir: Path,
) -> tuple[list[Beat], Path]:
    """Extend footage-beat video slots to fit the full broadcast clip.

    For each beat with ``kind == "footage"``, compare the clip's actual
    duration against the beat's video slot (which by default is driven
    by the narration timing). If the clip is longer, the narration is
    padded with silence at the end of that beat AND every subsequent
    beat's start/end is shifted by the delta — so compose_clips' video
    timeline now has room for the full footage clip without truncation.

    Returns ``(new_beats, new_audio_path)``. If no extension is needed,
    returns the originals unchanged (no audio rewrite).

    Implementation notes:
    - Clip duration is read once via ffprobe at extension-detection time.
    - Audio rewrite uses soundfile + numpy (already imported elsewhere)
      to splice silence at the end of each footage-extended beat.
    - Word timestamps inside extended beats are NOT shifted — the
      footage beat's words stay at their original positions, with the
      added silence trailing AFTER all words in that beat.
    """
    import numpy as np
    import soundfile as sf
    from dataclasses import replace

    # Detect which beats need extension and by how much.
    extensions: list[tuple[int, float]] = []  # (beat_idx, delta_s)
    for i, (kind, path) in enumerate(beat_resolutions):
        if kind != "footage":
            continue
        clip_dur = _ffprobe_duration(path)
        # The video slot size is the gap to the next beat (or the beat's
        # own end if it's the last beat). Match _video_timing's logic.
        if i + 1 < len(beats):
            slot_dur = beats[i + 1].start - beats[i].start
        else:
            slot_dur = beats[i].end - beats[i].start
        delta = clip_dur - slot_dur
        if delta > 0.05:  # ignore <50ms — not worth the audio rewrite
            extensions.append((i, delta))
            print(
                f"[compose_hybrid] beat {i} footage clip is {clip_dur:.2f}s "
                f"but the audio slot is {slot_dur:.2f}s — extending by "
                f"{delta:.2f}s (silence + shifted beats)"
            )

    if not extensions:
        return beats, audio_path

    # Rewrite the audio. Process extensions from LATEST to EARLIEST so
    # earlier insertions don't shift later insertion points.
    audio, sr = sf.read(str(audio_path))
    if audio.ndim == 1:
        new_audio = audio.copy()
    else:
        new_audio = audio.copy()  # (samples, channels)

    for i, delta in sorted(extensions, key=lambda x: -x[0]):
        # Insert silence at the NEXT beat's audio start, NOT at this
        # beat's end. ASR underestimates word-final consonants by
        # 50-200ms (Kokoro's "season" tail extends ~250ms past the
        # ASR-reported beat.end on the v14 Aguero render). Inserting
        # at beat.end cuts the word mid-tail and pushes the trailing
        # consonant 10+ seconds away on the timeline.
        # The next beat's start is the natural seam — all of beat[i]'s
        # audio (including ASR-underestimated tails) stays put; the
        # silence sits in the inter-beat gap; beat[i+1] onwards
        # shifts cleanly. For the last beat, fall back to beat.end +
        # 0.4s breath (no following beat to anchor against).
        if i + 1 < len(beats):
            insert_at = beats[i + 1].start
        else:
            insert_at = beats[i].end + 0.4
        sample_idx = int(round(insert_at * sr))
        sample_idx = max(0, min(sample_idx, len(new_audio)))
        silence_samples = int(round(delta * sr))
        if new_audio.ndim == 1:
            silence = np.zeros(silence_samples, dtype=new_audio.dtype)
        else:
            silence = np.zeros(
                (silence_samples, new_audio.shape[1]), dtype=new_audio.dtype
            )
        new_audio = np.concatenate(
            [new_audio[:sample_idx], silence, new_audio[sample_idx:]]
        )

    out_audio = cache_dir / "narration_extended.wav"
    sf.write(str(out_audio), new_audio, sr)
    print(f"[compose_hybrid] wrote {out_audio} (extended audio)")

    # Shift subsequent beats. For each extension at index i, every beat
    # j > i has its start AND end pushed by delta. Beat i itself has its
    # END pushed by delta (so the slot expands to fit footage) but its
    # START stays put. Process extensions in chronological order so
    # cumulative shifts add correctly.
    new_beats: list[Beat] = list(beats)
    for i, delta in sorted(extensions, key=lambda x: x[0]):
        for j in range(len(new_beats)):
            if j < i:
                continue
            b = new_beats[j]
            new_start = b.start + (delta if j > i else 0.0)
            new_end = b.end + delta  # both i and j>i get end shifted
            new_words = []
            for w in b.words:
                # Words inside beat i stay at their original times
                # (they're spoken BEFORE the inserted silence). Words in
                # beat j > i are shifted by the full delta.
                if j > i:
                    new_words.append(replace(w, start=w.start + delta, end=w.end + delta))
                else:
                    new_words.append(w)
            new_beats[j] = replace(b, start=new_start, end=new_end, words=new_words)

    return new_beats, out_audio


def compose_hybrid(
    beat_resolutions: list[tuple[str, Path]],
    beats: list[Beat],
    audio_path: Path,
    out_path: Path,
    cache_dir: Path,
    tail_hold_s: float = 0.0,
    rank_chips: list[tuple[int, Path]] | None = None,
) -> Path:
    """Compose a Short whose beats mix static images and footage clips.

    ``beat_resolutions`` is a per-beat ``(kind, path)`` list:

      * ``("image", path/to/img_NN.png)``  — Ken Burns over the image.
      * ``("footage", path/to/clip_NN.mp4)`` — real broadcast clip,
        produced by ``pipeline.footage.fetch_clip``. Trusted to be
        already 1080x1920 and roughly the right duration; this function
        does NOT re-trim or rescale.

    For each image beat we render a Ken Burns mp4 into the cache; for
    each footage beat we use the supplied mp4 directly. Then we hand the
    unified clip list to ``compose_clips`` which already knows how to
    crossfade-stitch + caption-overlay + tail-hold.

    The narration audio is the only audio in the final mp4 (footage
    clips' broadcast audio is dropped). Layered audio (broadcast under
    narrator) is a v2 — design note in feedback_sports_footage_is_usp.md.
    """
    if len(beat_resolutions) != len(beats):
        raise ValueError(
            f"beat_resolutions ({len(beat_resolutions)}) != beats ({len(beats)})"
        )

    # Footage extension — when a footage clip is longer than its beat's
    # audio slot (default narration timing), extend the slot so the FULL
    # broadcast clip plays through (Tyler's "AGUEROOOOO" call + ball
    # hitting the net). Inserts silence into narration at the end of
    # the footage beat and shifts subsequent beats by the same delta.
    # Without this the goal is cut mid-strike — caught on v5b critique.
    beats, audio_path = _extend_beats_for_footage(
        beats=beats,
        beat_resolutions=beat_resolutions,
        audio_path=audio_path,
        cache_dir=cache_dir,
    )

    video_start, video_dur = _video_timing(beats)
    clip_paths: list[Path] = []
    for i, (kind, src_path) in enumerate(beat_resolutions):
        clip_dst = cache_dir / f"clip_{i:02d}.mp4"
        if kind == "image":
            # Always re-render — the cached clip may be from a stale beat
            # duration. compose_clips loops/trims clips that don't match
            # video_dur[i], but giving it the right length up front keeps
            # the xfade math clean.
            image_to_kenburns_clip(src_path, video_dur[i], clip_dst)
            clip_paths.append(clip_dst)
        elif kind == "footage":
            # Use the footage mp4 as-is. compose_clips' _clip_filter will
            # loop/trim if the duration doesn't exactly match video_dur[i].
            clip_paths.append(src_path)
        else:
            raise ValueError(
                f"unknown beat kind {kind!r} at beat {i} "
                "(expected 'image' or 'footage')"
            )

    # Sports-style hybrid: word-pop centred captions + footage audio
    # layered under narrator. These are the SportsStoriesAnimated
    # defaults; pass overrides explicitly if a future channel using
    # compose_hybrid wants different behaviour.
    return compose_clips(
        clip_paths=clip_paths,
        beats=beats,
        audio_path=audio_path,
        out_path=out_path,
        cache_dir=cache_dir,
        tail_hold_s=tail_hold_s,
        pass_label="compose_hybrid",
        rank_chips=rank_chips,
        caption_style="per_word",
        layer_footage_audio=True,
        subscribe_button=True,
    )


def compose_clips(
    clip_paths: list[Path],
    beats: list[Beat],
    audio_path: Path,
    out_path: Path,
    cache_dir: Path,
    tail_hold_s: float = 0.0,
    pass_label: str = "compose_clips",
    rank_chips: list[tuple[int, Path]] | None = None,
    caption_style: str = "per_beat",
    layer_footage_audio: bool = False,
    subscribe_button: bool = False,
) -> Path:
    """Render the final Short from per-beat animated clips (mp4s).

    Mirrors ``compose()`` but consumes pre-rendered video clips instead
    of static images: skips the Ken Burns zoompan, keeps the xfade chain
    + caption overlay logic. Clips that are shorter than their beat get
    looped; longer clips get trimmed.

    ``caption_style`` (default ``"per_beat"``): set ``"per_word"`` to
    use the centred word-pop captions (TikTok / Submagic style) — same
    rendering used by the slideshow ``compose()`` path. SportsStoriesAnimated
    uses per_word for higher-retention caption sync.

    ``layer_footage_audio``: when True, ANY beat with ``kind == "footage"``
    has its source audio amix'd under the narration during that beat's
    window (volume from ``beat.footage["audio_mix"]``, default 0.7).
    Lets the broadcast call ("AGUEROOOOO!") play under the narrator.

    ``tail_hold_s``: freeze the last frame for this many seconds and
    pad the audio with matching silence.
    """
    assert len(clip_paths) == len(beats), "one clip per beat required"
    out_path.parent.mkdir(parents=True, exist_ok=True)

    # Normalise rank chip specs — accept (start, end, rank_int) or
    # (start, end, png_path) and ensure the PNGs exist on disk.
    rank_chips = _materialise_rank_chips(rank_chips, cache_dir)

    video_start, video_dur = _video_timing(beats)
    use_word_caps = caption_style == "per_word"

    # 1. Render caption PNGs.
    #    per_beat: one PNG per beat (legacy motion-path behaviour).
    #    per_word: one PNG per spoken word (TikTok / Submagic style),
    #    centred via _WORD_CAPTION_Y_FRAC. SportsStoriesAnimated wants
    #    this — higher retention than bottom-third per-beat captions.
    caption_paths: list[Path] = []
    all_words: list[tuple[int, float, float, str]] = []  # per_word only
    word_pngs: list[Path] = []
    if use_word_caps:
        for beat in beats:
            for w in beat.words:
                text = (w.text or "").strip()
                if text:
                    all_words.append(
                        (len(all_words), float(w.start), float(w.end), text)
                    )
        for gi, _ws, _we, text in all_words:
            wp = cache_dir / f"word_{gi:04d}.png"
            captions.render_word_caption(text, wp, canvas_w=WIDTH)
            word_pngs.append(wp)
    else:
        for i, beat in enumerate(beats):
            cp = cache_dir / f"caption_{i:02d}.png"
            if not cp.exists():
                captions.render_beat_caption(beat, cp, canvas_w=WIDTH, canvas_h=320)
            caption_paths.append(cp)

    # 2. Each clip is a real video input (no -loop / -t). The filter
    #    loops/trims it to video_dur[i] + XFADE so the next xfade has
    #    overlap.
    inputs: list[str] = []
    filter_chains: list[str] = []
    for i, clip in enumerate(clip_paths):
        clip_t = video_dur[i] + XFADE
        inputs += ["-i", str(clip)]
        filter_chains.append(f"[{i}:v]{_clip_filter(clip_t)}[v{i}]")

    # 3. Crossfade chain — audio-anchored offsets (Principle #1).
    if len(beats) == 1:
        filter_chains.append("[v0]copy[vchain]")
    else:
        prev = "v0"
        for i in range(1, len(beats)):
            label = f"x{i}" if i < len(beats) - 1 else "vchain"
            offset = max(0.0, video_start[i] - XFADE)
            filter_chains.append(
                f"[{prev}][v{i}]xfade=transition=fadeblack:duration={XFADE}:"
                f"offset={offset:.3f}[{label}]"
            )
            prev = label

    # 4. Caption inputs (looped to cover their on-screen window).
    n_clips = len(clip_paths)
    caption_input_idx_start = n_clips
    if use_word_caps:
        last_audio_t = max(b.end for b in beats) + tail_hold_s
        for gi, _ws, we, _text in all_words:
            loop_t = max(0.5, min(we + 0.5, last_audio_t + 0.5))
            inputs += ["-loop", "1", "-t", f"{loop_t:.3f}", "-i", str(word_pngs[gi])]
        n_caption_inputs = len(all_words)
    else:
        for i, cp in enumerate(caption_paths):
            inputs += [
                "-loop", "1",
                "-t", f"{video_dur[i] + XFADE:.3f}",
                "-i", str(cp),
            ]
        n_caption_inputs = len(caption_paths)

    # 4b. Rank chip inputs (one per rank). Each chip shape is
    #     (start_beat_idx, end_beat_idx, png_path) — the chip is on
    #     screen from beat[start].start to beat[end].start, covering
    #     the whole rank segment, not just the announcement beat.
    has_chips = bool(rank_chips)
    chip_input_idx_start = caption_input_idx_start + n_caption_inputs
    chip_specs: list[tuple[int, int, float, float]] = []  # (input_idx, start_idx, t_from, t_to)
    if has_chips:
        for k, (start_idx, end_idx, png_path) in enumerate(rank_chips):
            if not (0 <= start_idx < len(beats)):
                print(f"[compose_clips] rank chip start_idx {start_idx} out of range — skipping")
                continue
            t_from = video_start[start_idx]
            if 0 <= end_idx < len(beats):
                t_to = video_start[end_idx]
            else:
                t_to = video_start[start_idx] + video_dur[start_idx]
            chip_dur = (t_to - t_from) + 0.5
            inputs += [
                "-loop", "1",
                "-t", f"{chip_dur:.3f}",
                "-i", str(png_path),
            ]
            chip_specs.append((chip_input_idx_start + k, start_idx, t_from, t_to))

    # 5. Overlay captions on the audio timeline.
    last_sink = "v_pre_chips" if chip_specs else "vout"
    prev_label = "vchain"
    if use_word_caps:
        # Per-word centred overlays — one PNG flips on for each word's
        # [start, end] interval. Same logic as compose() slideshow path.
        word_y = int(HEIGHT * _WORD_CAPTION_Y_FRAC)
        n_words = len(all_words)
        for k, (gi, ws, we, _text) in enumerate(all_words):
            is_last_word = k == n_words - 1
            more_after = is_last_word and tail_hold_s > 0
            out_label = (
                last_sink if (is_last_word and not more_after) else f"vw{k}"
            )
            in_label = f"{caption_input_idx_start + gi}:v"
            filter_chains.append(
                f"[{prev_label}][{in_label}]overlay=x=(W-w)/2:y={word_y}:"
                f"enable='between(t,{ws:.3f},{we:.3f})'"
                f"[{out_label}]"
            )
            prev_label = out_label
    else:
        for i, beat in enumerate(beats):
            in_label = f"{caption_input_idx_start + i}:v"
            is_chain_end = i == len(beats) - 1
            out_label = (
                last_sink if (is_chain_end and tail_hold_s <= 0) else f"vc{i}"
            )
            cap_start, cap_end = _caption_window(beats, video_start, video_dur, i)
            if is_chain_end and tail_hold_s > 0:
                cap_end += tail_hold_s
            y_pos = HEIGHT - 460
            filter_chains.append(
                f"[{prev_label}][{in_label}]overlay=x=0:y={y_pos}:"
                f"enable='between(t,{cap_start:.3f},{cap_end:.3f})'"
                f"[{out_label}]"
            )
            prev_label = out_label

    # 6. Optional: hold the last frame for `tail_hold_s` extra seconds.
    if tail_hold_s > 0:
        filter_chains.append(
            f"[{prev_label}]tpad=stop_mode=clone:stop_duration={tail_hold_s:.3f}[{last_sink}]"
        )
        prev_label = last_sink

    # 6b. Rank chip overlays (top-left corner, one chip per ranked beat).
    #     Sinks to 'v_pre_sub' if a subscribe button follows, else 'vout'.
    chips_sink = "v_pre_sub" if subscribe_button else "vout"
    if chip_specs:
        CHIP_X, CHIP_Y = 60, 200
        for k, (in_idx, _b_idx, t_from, t_to) in enumerate(chip_specs):
            is_last_chip = k == len(chip_specs) - 1
            out_label = chips_sink if is_last_chip else f"vrank{k}"
            filter_chains.append(
                f"[{prev_label}][{in_idx}:v]overlay=x={CHIP_X}:y={CHIP_Y}:"
                f"enable='between(t,{t_from:.3f},{t_to:.3f})'"
                f"[{out_label}]"
            )
            prev_label = out_label

    # 6c. Subscribe button overlay (sports / hybrid path). Centred PIL-
    # rendered red rounded-rect with white "SUBSCRIBE" text, shown for
    # the last ~3s. Programmatic render → guaranteed legibility (vs
    # asking diffusion to render text inside the closer cartoon, which
    # tends to come out garbled or absent — caught on v1 Iniesta render).
    sub_input_idx = None
    if subscribe_button:
        # If chips weren't drawn, the chain's current sink is whatever
        # caption/tpad produced — re-alias its 'vout' output to 'v_pre_sub'.
        if not chip_specs:
            for j in range(len(filter_chains) - 1, -1, -1):
                if filter_chains[j].endswith("[vout]"):
                    filter_chains[j] = filter_chains[j][:-len("[vout]")] + "[v_pre_sub]"
                    break
            prev_label = "v_pre_sub"
        sub_path = cache_dir / "subscribe_button.png"
        captions.render_subscribe_button(sub_path)
        sub_loop_t = max(0.5, (max(b.end for b in beats) + tail_hold_s) + 0.5)
        inputs += ["-loop", "1", "-t", f"{sub_loop_t:.3f}", "-i", str(sub_path)]
        sub_input_idx = caption_input_idx_start + n_caption_inputs + len(chip_specs)
        sub_total = max(b.end for b in beats) + tail_hold_s
        sub_start = max(0.0, sub_total - 3.0)
        # y offset: lift up from centre slightly so it doesn't sit on
        # caption row. Caption is centred at HEIGHT*0.45 ≈ 864; place
        # button below that at HEIGHT*0.62.
        sub_y = int(HEIGHT * 0.62)
        filter_chains.append(
            f"[v_pre_sub][{sub_input_idx}:v]overlay=x=(W-w)/2:y={sub_y}:"
            f"enable='between(t,{sub_start:.3f},{sub_total:.3f})'[vout]"
        )

    audio_idx = (
        caption_input_idx_start + n_caption_inputs + len(chip_specs)
        + (1 if subscribe_button else 0)
    )
    max_duration = max(b.end for b in beats) + 0.4 + tail_hold_s

    # Footage audio layering — for each ``kind: footage`` beat, take
    # that clip's audio stream, trim/delay it to the beat's window on
    # the output timeline, and amix it under the narration. The mix
    # volume comes from beat.footage["audio_mix"] (0.0-1.0). Narration
    # stays full volume; footage rides under.
    audio_map_label = f"{audio_idx}:a"
    audio_via_complex = False  # set True when audio routes through filter_complex
    if layer_footage_audio:
        footage_streams: list[str] = []
        duck_windows: list[tuple[float, float]] = []
        for i, b in enumerate(beats):
            if b.kind != "footage":
                continue
            mix_vol = float((b.footage or {}).get("audio_mix") or 0.7)
            if mix_vol <= 0:
                continue  # explicitly muted
            start_ms = int(round(video_start[i] * 1000))
            filter_chains.append(
                f"[{i}:a]atrim=duration={video_dur[i]:.3f},"
                f"asetpts=PTS-STARTPTS,"
                f"adelay={start_ms}|{start_ms},"
                f"volume={mix_vol:.2f}[fa{i}]"
            )
            footage_streams.append(f"[fa{i}]")
            # When the footage clip has a black-intro pre-pad, the narrator
            # speaks the beat's setup line ("Last kick of the season") OVER
            # the black — narration must stay audible there. Start the duck
            # only AFTER the beat's narration ends. Without this, the silent
            # black intro would silence the narration too, leaving nothing
            # during the suspense moment.
            pre_pad_s = float((b.footage or {}).get("pre_pad_s") or 0.0)
            if pre_pad_s > 0.05:
                duck_windows.append((b.end, video_start[i] + video_dur[i]))
            else:
                duck_windows.append((video_start[i], video_start[i] + video_dur[i]))
        if footage_streams:
            # Duck the narration to silence during footage windows so the
            # broadcast commentary plays solo (Tyler's "AGUEROOOOO" not
            # fighting our narrator saying "Aguero scores"). Each window
            # contributes a `between(t,a,b)` predicate; ffmpeg `enable`
            # ORs them via `+` (sum is nonzero when any window matches).
            enable_or = "+".join(
                f"between(t,{s:.3f},{e:.3f})" for s, e in duck_windows
            )
            filter_chains.append(
                f"[{audio_idx}:a]volume=0:enable='{enable_or}'[narr_ducked]"
            )
            srcs = "[narr_ducked]" + "".join(footage_streams)

            # apad must live INSIDE the complex filter when audio is
            # routed through it — ffmpeg rejects -af on a stream that
            # came from filter_complex ("simple and complex filtering
            # cannot be used together for the same stream").
            tail_clause = (
                f",apad=pad_dur={tail_hold_s:.3f}" if tail_hold_s > 0 else ""
            )
            filter_chains.append(
                f"{srcs}amix=inputs={len(footage_streams) + 1}:"
                f"duration=first:normalize=0{tail_clause}[a_mix]"
            )
            audio_map_label = "[a_mix]"
            audio_via_complex = True

    filter_complex = ";".join(filter_chains)

    cmd = [
        "ffmpeg", "-y",
        *inputs,
        "-i", str(audio_path),
        "-filter_complex", filter_complex,
        "-map", "[vout]",
        "-map", audio_map_label,
        "-c:v", "libx264",
        "-pix_fmt", "yuv420p",
        "-r", str(FPS),
        "-c:a", "aac",
        "-b:a", "192k",
        "-movflags", "+faststart",
        "-t", f"{max_duration:.3f}",
    ]
    if tail_hold_s > 0 and not audio_via_complex:
        # Pad audio with silence so the held video frames have a matching
        # silent tail rather than a sudden audio cutoff. Skip when audio
        # routes through filter_complex (we already folded apad into the
        # amix chain — ffmpeg rejects -af on a complex-filtered stream).
        cmd += ["-af", f"apad=pad_dur={tail_hold_s:.3f}"]
    cmd += [str(out_path)]

    print("[compose_clips] running ffmpeg…")
    with _tlm.timed(
        "ffmpeg_compose",
        category="pipeline",
        job_id=os.environ.get("YTFACTORY_JOB_ID") or None,
        metadata={
            "phase": pass_label,
            "pass": pass_label,
            "n_inputs": len(clip_paths),
            "duration_s": round(max_duration, 2),
            "tail_hold_s": tail_hold_s,
        },
    ) as t:
        result = subprocess.run(cmd, capture_output=True, text=True)
        t.add(metadata={"return_code": result.returncode})
        if result.returncode != 0:
            print("[compose_clips] ffmpeg stderr (last 3000 chars):")
            print(result.stderr[-3000:])
            raise RuntimeError(f"ffmpeg failed (exit {result.returncode})")
    print(f"[compose_clips] wrote {out_path}")
    return out_path
