#!/usr/bin/env python3
"""Extract every ```mermaid block from docs/*.md and render it to PNG.

Usage:
    .venv/bin/python scripts/render_mermaid.py

Writes to docs/diagrams/<doc-stem>-<n>-<title>.png and emits a
docs/diagrams/index.md listing every diagram with its source location.

Diagram titles come from the nearest preceding `## ` or `### ` heading,
slugified. The `n` index keeps duplicate headings unique.
"""
from __future__ import annotations

import re
import subprocess
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
DOCS = ROOT / "docs"
OUT = DOCS / "diagrams"

MERMAID_BLOCK = re.compile(r"```mermaid\n(.*?)\n```", re.DOTALL)
HEADING = re.compile(r"^(#{1,4})\s+(.+?)\s*$", re.M)


def slugify(text: str, max_len: int = 50) -> str:
    text = re.sub(r"[^a-zA-Z0-9]+", "-", text).strip("-").lower()
    return text[:max_len] or "untitled"


def nearest_heading_before(md: str, idx: int) -> str:
    """Walk backwards from `idx` to the nearest `##`/`###` heading."""
    headings = list(HEADING.finditer(md, 0, idx))
    if not headings:
        return "diagram"
    return headings[-1].group(2).strip()


def extract_blocks(md_path: Path):
    text = md_path.read_text()
    for n, m in enumerate(MERMAID_BLOCK.finditer(text), start=1):
        heading = nearest_heading_before(text, m.start())
        yield n, heading, m.group(1)


def render_png(diagram: str, out_png: Path) -> None:
    out_png.parent.mkdir(parents=True, exist_ok=True)
    src = out_png.with_suffix(".mmd")
    src.write_text(diagram)
    # mmdc reads .mmd, writes png. -t dark gives a nice slate theme that
    # matches the operator UI.
    cmd = [
        "mmdc",
        "-i", str(src),
        "-o", str(out_png),
        "-t", "dark",
        "-b", "#0f172a",
        "-w", "1600",
        "-p", str(ROOT / "scripts" / "mermaid_puppeteer.json"),
    ]
    subprocess.run(cmd, check=True, cwd=str(ROOT), capture_output=True)
    src.unlink()  # don't leave intermediate .mmd files


def main() -> int:
    if not OUT.parent.exists():
        print(f"docs/ not found at {DOCS}", file=sys.stderr)
        return 2

    OUT.mkdir(parents=True, exist_ok=True)
    # Wipe stale PNGs so re-running is idempotent.
    for old in OUT.glob("*.png"):
        old.unlink()

    index_lines = [
        "# Diagram index",
        "",
        "Auto-generated by `scripts/render_mermaid.py`. PNGs derived from",
        "the ```mermaid blocks in the source docs.",
        "",
    ]

    docs = sorted(p for p in DOCS.glob("*.md") if p.name != "diagrams.md")
    total = 0
    for md in docs:
        if md.parent != DOCS:
            continue
        rel = md.relative_to(ROOT)
        sub_lines = [f"## {rel}", ""]
        any_in_doc = False
        for n, heading, diagram in extract_blocks(md):
            stem = f"{md.stem}-{n:02d}-{slugify(heading)}"
            png = OUT / f"{stem}.png"
            try:
                render_png(diagram, png)
            except subprocess.CalledProcessError as e:
                print(f"FAILED {md.name} #{n} ({heading}): {e.stderr.decode()[:200]}",
                      file=sys.stderr)
                continue
            sub_lines.append(f"- **{heading}** — `diagrams/{png.name}`")
            print(f"  rendered {png.relative_to(ROOT)}")
            total += 1
            any_in_doc = True
        if any_in_doc:
            sub_lines.append("")
            index_lines.extend(sub_lines)

    (OUT / "index.md").write_text("\n".join(index_lines))
    print(f"\n{total} PNG diagram(s) written to {OUT.relative_to(ROOT)}/")
    return 0


if __name__ == "__main__":
    sys.exit(main())
