"""CastContract — Stage 3.5 (cast.json authoring) as an orchestrated stage.

Wraps the existing ``pipeline.llm.cast.author_cast`` prompt in the
orchestrator's contract pattern: pulls constraints from
:mod:`pipeline.llm.cast_lint` (the same gates the renderer + post-
render critic run), embeds them in the prompt with
validator-derived BAD examples, validates inline, and asks the
orchestrator to regenerate on any error-level Fix.

Mirrors :class:`pipeline.llm.contracts.rewrite_contract.RewriteContract`
in shape and intent — same authoring story, applied to the next
fragility surface.

Also closes the v5-smoke gap where cast.json was generated by a
single-shot LLM call with no validation: a cast that returned
``{"supporting": "should be a list"}`` (the prompts.py drift bug we
also saw) would have crashed the renderer minutes later. With this
contract the orchestrator catches it on attempt 1 and regenerates.
"""

from __future__ import annotations

from dataclasses import dataclass

from .. import cast_lint
from ..fix import Fix
from ..orchestrator import Constraint, StageContext
from .base import render_constraints_block, render_fixes_block


@dataclass
class CastContract:
    """Orchestrated cast.json author. See module docstring."""

    name: str = "cast"
    fanout: int = 1
    artifact_paths: tuple[str, ...] = ("cast", "cast.narrator", "cast.supporting")

    def gather_constraints(self, ctx: StageContext) -> list[Constraint]:
        """Constraints sourced from cast_lint.

        Errors are the SHAPE rules (no narrator → can't render anything).
        Warnings are the soft style rules (hair conflicts, long descriptions,
        text-bait wardrobe) — surfaced in the prompt so the model knows
        to avoid them, surfaced again on the result so an operator can
        edit cast.json before re-rendering.
        """
        return [
            Constraint(
                name="narrator_required",
                severity="error",
                description=(
                    "Output MUST include a 'narrator' object with a "
                    "non-empty 'description' field. Without this the "
                    "renderer has no character to draw and the entire "
                    "Short fails."
                ),
                examples_good=(
                    '{"narrator": {"description": "Round-headed adult woman in flat '
                    '2D crayon style…", "default_emotion": "frustrated", '
                    '"age_band": "adult", "gender": "female"}, "supporting": []}',
                ),
                examples_bad=(
                    '{"description": "..."}            // missing narrator wrapper',
                    '{"narrator": "a baker"}            // narrator must be an OBJECT',
                    '{"narrator": {"name": "Sarah"}}    // missing description',
                ),
            ),
            Constraint(
                name="supporting_array",
                severity="error",
                description=(
                    "If 'supporting' is present it MUST be an array of "
                    "objects, never a string or a single object. The "
                    "renderer iterates over it."
                ),
                examples_bad=(
                    '{"supporting": "Lily"}',
                    '{"supporting": {"name": "Lily"}}',
                ),
            ),
            Constraint(
                name="narrator_self_conflict",
                severity="warning",
                description=(
                    "The narrator description MUST pick ONE hair length AND "
                    "ONE hair styling. Diffusion averages between conflicting "
                    "tokens and produces drift across beats."
                ),
                examples_good=cast_lint.EXAMPLES_GOOD_NARRATOR_DESC,
                examples_bad=cast_lint.EXAMPLES_BAD_NARRATOR_DESC,
            ),
            Constraint(
                name="description_has_text_token",
                severity="warning",
                description=(
                    "Wardrobe MUST NOT include text-bait tokens like "
                    "'logo', 'label', 'writing', 'letters', 'text', "
                    "'wording'. SDXL / FLUX render these as in-image "
                    "gibberish text. Describe shape + colour + icon "
                    "instead."
                ),
                examples_bad=(
                    "Yellow t-shirt with the logo of her bakery",
                    "Apron with embroidered text saying 'Bake Boss'",
                ),
            ),
            Constraint(
                name="description_too_long",
                severity="warning",
                description=(
                    f"Each character description MUST stay under "
                    f"~{cast_lint._DESC_MAX_WORDS} words. Diffusion "
                    f"attention drops past that and the back half of the "
                    f"description gets ignored."
                ),
            ),
        ]

    def build_prompt(self, ctx: StageContext, constraints: list[Constraint]) -> str:
        """Build the first-attempt cast prompt.

        Pulls the upstream Script (from the orchestrator's RenderJob.upstream)
        and the channel's image_style_prefix. Embeds the constraints block
        at the top so the model anchors on rules first.
        """
        upstream = ctx.upstream or {}
        script = upstream.get("script") or ctx.raw_input.get("script") or {}
        narration = (script.get("narration") or
                     ctx.raw_input.get("narration") or "").strip()
        title = (script.get("title_options", [""])[0] if script.get("title_options")
                 else ctx.raw_input.get("title", "")).strip()
        story_text = f"{title}\n\n{narration}" if title else narration

        cfg = ctx.channel_cfg or {}
        style_prefix = (cfg.get("image_style_prefix") or "").strip()
        if not style_prefix:
            # The orchestrator can't help with config-missing; surface
            # the same error the legacy path raised so callers don't
            # silently get a default style.
            raise ValueError("channel config missing image_style_prefix — "
                             "cast cannot author without an aesthetic anchor")

        rules_block = render_constraints_block(constraints)

        return (
            "You are designing recurring cartoon characters for a YouTube "
            "Shorts narrator + the supporting cast they talk about. The "
            "characters will be drawn in this aesthetic on every beat:\n\n"
            "CHANNEL AESTHETIC (locked):\n"
            f'"""\n{style_prefix[:1500]}\n"""\n\n'
            f"{rules_block}\n"
            "ADDITIONAL CRAFT GUIDANCE:\n"
            "  - Match the narrator's age and gender to the inferred "
            "demographic of the source story (\"my MIL\" → middle-aged or "
            "elder OP; \"my fiancé\" → late 20s-40s OP; \"my parents\" → "
            "teen / young-adult OP).\n"
            "  - Wardrobe MUST be specific to the inferred demographic. A "
            "60yo grandmother in a yellow t-shirt and blue jeans is a "
            "render bug.\n"
            "  - For each named or relational character in the story "
            "(e.g. \"Lily\", \"my MIL Carol\"), add a supporting entry "
            "with name, aliases, and a visually distinct description.\n"
            "  - Each supporting character needs a distinct visual "
            "(different hair colour OR age OR wardrobe from the narrator). "
            "Without this, diffusion paints them as the narrator.\n\n"
            "Source story:\n"
            f'"""\n{story_text[:5000]}\n"""\n\n'
            "Return ONLY a JSON object with this exact shape (no prose, no "
            "markdown fences):\n"
            "{\n"
            '  "narrator": {\n'
            '    "description": "<one-line cartoon character description>",\n'
            '    "default_emotion": "<dominant emotional tone>",\n'
            '    "age_band": "child|teen|young-adult|adult|middle-aged|elder",\n'
            '    "gender": "female|male|non-binary|unspecified"\n'
            "  },\n"
            '  "supporting": [\n'
            "    {\n"
            '      "name": "<name or relation>",\n'
            '      "aliases": ["<other forms used in the narration>"],\n'
            '      "description": "<one-line cartoon description, visually distinct>"\n'
            "    }\n"
            "  ]\n"
            "}"
        )

    def regen_prompt(
        self,
        ctx: StageContext,
        prev_output: dict,
        fixes: list[Fix],
    ) -> str:
        """Diff-style regen prompt: hand the model its prior output + the failures."""
        diag = render_fixes_block(fixes)
        narr_prev = prev_output.get("narrator") if isinstance(prev_output, dict) else None
        sup_prev = prev_output.get("supporting") if isinstance(prev_output, dict) else None

        return (
            "Your previous cast.json failed one or more rules. Patch ONLY "
            "the broken parts — keep the same characters, same story "
            "fit, just fix the cited issues.\n\n"
            f"Previous narrator: {narr_prev!r}\n"
            f"Previous supporting: {sup_prev!r}\n\n"
            f"{diag}\n"
            "Return ONLY a JSON object with the same shape as before "
            '(narrator + supporting list).'
        )

    def validate(self, ctx: StageContext, output: dict) -> list[Fix]:
        """Run cast_lint and translate every issue into a Fix."""
        issues = cast_lint.check_cast(output)
        return [
            Fix(
                constraint=i.code,
                reason=i.message,
                severity=i.severity,
                target_stage=self.name,
                target_path=i.target_path,
                source_judge="cast_lint",
            )
            for i in issues
        ]
