apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: ytfactory
resources:
  - configmap.yaml
  - deployment.yaml
  - svc.yaml
  - ingress.yaml
  - pvc.yaml
  - network-policy.yaml
  - gatus-check.yaml
  - sealed-secrets.yaml
images:
  - name: ytfactory-web
    newName: ghcr.io/rohitsingh30/ytfactory-web
    newTag: awaiting-validated-image
  - name: ytfactory-api
    newName: ghcr.io/rohitsingh30/ytfactory-api
    newTag: awaiting-validated-image
